[package]
name = "sigil-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
sigil-ast = { path = "../sigil-ast" }
sigil-lexer = { path = "../sigil-lexer" }
sigil-parser = { path = "../sigil-parser" }
thiserror = "1.0"
serde_json = "1.0"
